Nama : Nanda Pesona Putri

NIM : 2409116101

# **CHECKPOINT 1**

Data Source : Kaggle.com

Judul Data : Food Delivery Order History Data

# **BUSINESS UNDERSTANDING**

## **Business Objective**

Tujuan utama dari dataset yang saya pilih adalah untuk mengoptimalkan proses pengiriman dan meningkatkan kepuasan pelanggan, sekaligus meningkatkan efisiensi operasional dan keuntungan perusahaan. Dengan menganalisis data pesanan, waktu pengiriman, jenis makanan, perusahaan dapat mengidentifikasi area-area yang perlu perbaikan, seperti mempercepat waktu pengiriman, mengoptimalkan rute pengiriman, dan menawarkan promosi atau harga yang lebih sesuai dengan permintaan.

## **Assess Situation**

 Situasi bisnis yang mendasari analisis ini andalah isu dalam bisnis pengiriman makanan seperti persaingan ketat, efisiensi operasional, dan kepuasan pelanggan. Dengan menganalisis preferensi pelanggan dan pola pesanan, bisnis dapat menyesuaikan strategi pemasaran serta meningkatkan layanan agar tetap kompetitif di tengah maraknya platform pengiriman makanan. Selain itu, data pengiriman dapat digunakan untuk mengatasi isu keterlambatan dan optimasi rute, yang sering menjadi faktor utama dalam kepuasan pelanggan.

## **Data Mining Goals**

meningkatkan efisiensi operasional dan kepuasan pelanggan melalui prediksi waktu pengiriman, segmentasi pelanggan, analisis tren permintaan, dan optimasi rute pengiriman. Selain itu, perusahaan bertujuan untuk menilai efektivitas promosi, dan mengidentifikasi makanan terlaris serta margin keuntungan untuk merencanakan strategi harga dan menu yang lebih baik. Semua tujuan ini mendukung keputusan berbasis data untuk meningkatkan keuntungan dan pengalaman pelanggan.

## **Project Plan**

Tahapan proyek dimulai dengan memahami struktur data, termasuk data data yang ada di dalamnya, seperti id resto, pesanan, serta rating dari pelanggan. Selanjutnya, eksplorasi data dilakukan dengan melihat distribusi pesanan berdasarkan hari, jam sibuk, restoran yang paling sering dipesan, metode pembayaran yang banyak digunakan, serta rata-rata harga pesanan.

# **CHECKPOINT 2**

## **DATA UNDERSTANDING**

Data Source : https://www.kaggle.com/datasets/sujalsuthar/food-delivery-order-history-data?resource=download

Judul Data : Food Delivery Order History Data

Tahap 1 : mengimport pandas ke colab untuk membaca file csv

In [12]:
import pandas as pd

In [13]:
df = pd.read_csv("/content/archive (1).zip")

In [14]:
df

,Restaurant ID,Restaurant name,Subzone,City,Order ID,Order Placed At,Order Status,Delivery,Distance,Items in order,...,Rating,Review,Cancellation / Rejection reason,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes),Order Ready Marked,Customer complaint tag,Customer ID
0,20320607,Swaad,Sector 4,Delhi NCR,6168884918,"11:38 PM, September 10 2024",Delivered,Zomato Delivery,3km,"1 x Grilled Chicken Jamaican Tender, 1 x Grill...",...,NaN,NaN,NaN,NaN,NaN,18.35,11.6,Correctly,NaN,5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...
1,20320607,Swaad,Sector 4,Delhi NCR,6170707559,"11:34 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Fries, 1 x Fried Chicken Angara ...",...,NaN,NaN,NaN,NaN,NaN,16.95,3.6,Correctly,NaN,0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...
2,20320607,Swaad,Sector 4,Delhi NCR,6169375019,"03:52 PM, September 10 2024",Delivered,Zomato Delivery,<1km,1 x Bone in Peri Peri Grilled Chicken,...,NaN,NaN,NaN,NaN,NaN,14.05,12.2,Correctly,NaN,f93362f5ce5382657482d164e368186bcec9c6225fd93d...
3,20320607,Swaad,Sector 4,Delhi NCR,6151677434,"03:45 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Fried Chicken Ghostbuster Tender, 1 x Anga...",...,4.0,NaN,NaN,NaN,NaN,19.00,3.3,Correctly,NaN,1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...
4,20320607,Swaad,Sector 4,Delhi NCR,6167540897,"03:04 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Krispers, 1 x Fried Chicken Anga...",...,NaN,NaN,NaN,NaN,NaN,15.97,1.0,Correctly,NaN,d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21316,21467440,The Chicken Junction,Chittaranjan Park,Delhi NCR,6568490993,"03:26 AM, January 30 2025",Delivered,Zomato Delivery,5km,1 x Fried Chicken Desi Peri Peri Bites (Bone),...,NaN,NaN,NaN,NaN,NaN,14.32,9.0,Correctly,Wrong item(s) delivered,c6ee80eb35f2ef1630fd93ea88f8c0ac27eff57229a6d5...
21317,21467440,The Chicken Junction,Chittaranjan Park,Delhi NCR,6564842673,"02:44 AM, January 29 2025",Delivered,Zomato Delivery,5km,1 x Fried Chicken 65 Masala Boneless Bites,...,NaN,NaN,NaN,NaN,NaN,NaN,10.8,Missed,NaN,d2a0153ba6512894c1bebe974f6898ba10df50abc2c954...
21318,21523055,Masala Junction,Sector 4,Delhi NCR,6553527557,"10:05 PM, January 24 2025",Delivered,Zomato Delivery,8km,1 x Korean Fried Chicken Slider,...,5.0,Yummy food! Delicious food! Lip smacking food!...,NaN,NaN,NaN,16.27,9.4,Incorrectly,NaN,0b6168cbaf96aa5a0ae6b46d19d83ec9cad0d9508d43d7...
21319,21523055,Masala Junction,Sector 4,Delhi NCR,6541170157,"02:27 PM, January 21 2025",Delivered,Zomato Delivery,9km,1 x Ooh Saucy Fries,...,4.0,The peri peri fries were truly so tasty and de...,NaN,NaN,NaN,12.77,1.3,Correctly,NaN,410b3e056e511e3423d9497c629ca897f91cace2a2a732...
21320,21523055,Masala Junction,Sector 4,Delhi NCR,6543973010,"02:55 AM, January 21 2025",Delivered,Zomato Delivery,3km,1 x Grilled Chicken Jamaican Slider,...,NaN,NaN,NaN,NaN,NaN,16.52,8.7,Correctly,NaN,1f885b307de98a52c7b6f75a8813cc130e3049ad0be017...

In [15]:
print(df.head())

   Restaurant ID Restaurant name   Subzone       City    Order ID  \
0       20320607           Swaad  Sector 4  Delhi NCR  6168884918
1       20320607           Swaad  Sector 4  Delhi NCR  6170707559
2       20320607           Swaad  Sector 4  Delhi NCR  6169375019
3       20320607           Swaad  Sector 4  Delhi NCR  6151677434
4       20320607           Swaad  Sector 4  Delhi NCR  6167540897

               Order Placed At Order Status         Delivery Distance  \
0  11:38 PM, September 10 2024    Delivered  Zomato Delivery      3km
1  11:34 PM, September 10 2024    Delivered  Zomato Delivery      2km
2  03:52 PM, September 10 2024    Delivered  Zomato Delivery     <1km
3  03:45 PM, September 10 2024    Delivered  Zomato Delivery      2km
4  03:04 PM, September 10 2024    Delivered  Zomato Delivery      2km

                                      Items in order  ... Rating Review  \
0  1 x Grilled Chicken Jamaican Tender, 1 x Grill...  ...    NaN    NaN
1  1 x Peri Peri Fries, 1 x Fried Chicken Angara ...  ...    NaN    NaN
2              1 x Bone in Peri Peri Grilled Chicken  ...    NaN    NaN
3  1 x Fried Chicken Ghostbuster Tender, 1 x Anga...  ...    4.0    NaN
4  1 x Peri Peri Krispers, 1 x Fried Chicken Anga...  ...    NaN    NaN

   Cancellation / Rejection reason  Restaurant compensation (Cancellation)  \
0                              NaN                                     NaN
1                              NaN                                     NaN
2                              NaN                                     NaN
3                              NaN                                     NaN
4                              NaN                                     NaN

   Restaurant penalty (Rejection)  KPT duration (minutes)  \
0                             NaN                   18.35
1                             NaN                   16.95
2                             NaN                   14.05
3                             NaN                   19.00
4                             NaN                   15.97

   Rider wait time (minutes)  Order Ready Marked  Customer complaint tag  \
0                       11.6           Correctly                     NaN
1                        3.6           Correctly                     NaN
2                       12.2           Correctly                     NaN
3                        3.3           Correctly                     NaN
4                        1.0           Correctly                     NaN

                                         Customer ID
0  5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...
1  0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...
2  f93362f5ce5382657482d164e368186bcec9c6225fd93d...
3  1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...
4  d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...

[5 rows x 29 columns]

Melihat jumlah baris dan kolom

In [32]:
df.shape

(21321, 29)

Cek tipedata setiap kolom

In [33]:
df.dtypes

Restaurant ID                                           int64
Restaurant name                                        object
Subzone                                                object
City                                                   object
Order ID                                                int64
Order Placed At                                        object
Order Status                                           object
Delivery                                               object
Distance                                               object
Items in order                                         object
Instructions                                           object
Discount construct                                     object
Bill subtotal                                         float64
Packaging charges                                     float64
Restaurant discount (Promo)                           float64
Restaurant discount (Flat offs, Freebies & others)    float64
Gold discount                                         float64
Brand pack discount                                   float64
Total                                                 float64
Rating                                                float64
Review                                                 object
Cancellation / Rejection reason                        object
Restaurant compensation (Cancellation)                float64
Restaurant penalty (Rejection)                        float64
KPT duration (minutes)                                float64
Rider wait time (minutes)                             float64
Order Ready Marked                                     object
Customer complaint tag                                 object
Customer ID                                            object
dtype: object

Statistik deskriptif

In [34]:
df.describe()

,Restaurant ID,Order ID,Bill subtotal,Packaging charges,Restaurant discount (Promo),"Restaurant discount (Flat offs, Freebies & others)",Gold discount,Brand pack discount,Total,Rating,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes)
count,2.132100e+04,2.132100e+04,21321.000000,21321.000000,21321.000000,21321.000000,21321.000000,21321.000000,21321.000000,2491.000000,133.000000,3.0,21026.000000,21153.000000
mean,2.074413e+07,6.354622e+09,750.076838,32.564592,65.091816,31.795058,0.099128,3.039324,682.616113,4.356885,356.409549,0.0,17.332960,4.825070
std,2.447193e+05,1.230263e+08,498.759428,22.235898,85.401604,131.487091,3.264261,17.070780,465.313977,1.181472,328.128240,0.0,6.283388,4.982591
min,2.032061e+07,6.086767e+09,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000,52.500000,1.000000,83.580000,0.0,0.000000,0.100000
25%,2.063570e+07,6.250751e+09,459.000000,18.450000,0.000000,0.000000,0.000000,0.000000,387.450000,4.000000,191.950000,0.0,13.380000,1.000000
50%,2.065987e+07,6.357715e+09,629.000000,28.450000,80.000000,0.000000,0.000000,0.000000,597.450000,5.000000,272.580000,0.0,16.330000,3.100000
75%,2.088265e+07,6.456827e+09,899.000000,39.950000,100.000000,0.000000,0.000000,0.000000,837.900000,5.000000,397.840000,0.0,20.050000,7.400000
max,2.152306e+07,6.573392e+09,16080.000000,603.000000,4020.000000,7787.000000,280.100000,554.800000,12663.000000,5.000000,3236.980000,0.0,90.870000,73.800000

# **DATA PREPARATION**

## **Tahap 1 : Melakukan import file**

In [38]:
import pandas as pd

file = "/content/archive (1).zip"

df = pd.read_csv(file)
df

,Restaurant ID,Restaurant name,Subzone,City,Order ID,Order Placed At,Order Status,Delivery,Distance,Items in order,...,Rating,Review,Cancellation / Rejection reason,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes),Order Ready Marked,Customer complaint tag,Customer ID
0,20320607,Swaad,Sector 4,Delhi NCR,6168884918,"11:38 PM, September 10 2024",Delivered,Zomato Delivery,3km,"1 x Grilled Chicken Jamaican Tender, 1 x Grill...",...,NaN,NaN,NaN,NaN,NaN,18.35,11.6,Correctly,NaN,5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...
1,20320607,Swaad,Sector 4,Delhi NCR,6170707559,"11:34 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Fries, 1 x Fried Chicken Angara ...",...,NaN,NaN,NaN,NaN,NaN,16.95,3.6,Correctly,NaN,0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...
2,20320607,Swaad,Sector 4,Delhi NCR,6169375019,"03:52 PM, September 10 2024",Delivered,Zomato Delivery,<1km,1 x Bone in Peri Peri Grilled Chicken,...,NaN,NaN,NaN,NaN,NaN,14.05,12.2,Correctly,NaN,f93362f5ce5382657482d164e368186bcec9c6225fd93d...
3,20320607,Swaad,Sector 4,Delhi NCR,6151677434,"03:45 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Fried Chicken Ghostbuster Tender, 1 x Anga...",...,4.0,NaN,NaN,NaN,NaN,19.00,3.3,Correctly,NaN,1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...
4,20320607,Swaad,Sector 4,Delhi NCR,6167540897,"03:04 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Krispers, 1 x Fried Chicken Anga...",...,NaN,NaN,NaN,NaN,NaN,15.97,1.0,Correctly,NaN,d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21316,21467440,The Chicken Junction,Chittaranjan Park,Delhi NCR,6568490993,"03:26 AM, January 30 2025",Delivered,Zomato Delivery,5km,1 x Fried Chicken Desi Peri Peri Bites (Bone),...,NaN,NaN,NaN,NaN,NaN,14.32,9.0,Correctly,Wrong item(s) delivered,c6ee80eb35f2ef1630fd93ea88f8c0ac27eff57229a6d5...
21317,21467440,The Chicken Junction,Chittaranjan Park,Delhi NCR,6564842673,"02:44 AM, January 29 2025",Delivered,Zomato Delivery,5km,1 x Fried Chicken 65 Masala Boneless Bites,...,NaN,NaN,NaN,NaN,NaN,NaN,10.8,Missed,NaN,d2a0153ba6512894c1bebe974f6898ba10df50abc2c954...
21318,21523055,Masala Junction,Sector 4,Delhi NCR,6553527557,"10:05 PM, January 24 2025",Delivered,Zomato Delivery,8km,1 x Korean Fried Chicken Slider,...,5.0,Yummy food! Delicious food! Lip smacking food!...,NaN,NaN,NaN,16.27,9.4,Incorrectly,NaN,0b6168cbaf96aa5a0ae6b46d19d83ec9cad0d9508d43d7...
21319,21523055,Masala Junction,Sector 4,Delhi NCR,6541170157,"02:27 PM, January 21 2025",Delivered,Zomato Delivery,9km,1 x Ooh Saucy Fries,...,4.0,The peri peri fries were truly so tasty and de...,NaN,NaN,NaN,12.77,1.3,Correctly,NaN,410b3e056e511e3423d9497c629ca897f91cace2a2a732...
21320,21523055,Masala Junction,Sector 4,Delhi NCR,6543973010,"02:55 AM, January 21 2025",Delivered,Zomato Delivery,3km,1 x Grilled Chicken Jamaican Slider,...,NaN,NaN,NaN,NaN,NaN,16.52,8.7,Correctly,NaN,1f885b307de98a52c7b6f75a8813cc130e3049ad0be017...

##**Tahap 2 : Mising Value**

Menampilkan hanya kolom yang memiliki Mising Value

In [42]:
print((df.isna().sum() / len(df)) * 100)

Restaurant ID                                          0.000000
Subzone                                                0.000000
City                                                   0.000000
Order ID                                               0.000000
Order Status                                           0.000000
Delivery                                               0.000000
Distance                                               0.000000
Items in order                                         0.000000
Instructions                                          96.623048
Discount construct                                    25.786783
Bill subtotal                                          0.000000
Restaurant discount (Promo)                            0.000000
Restaurant discount (Flat offs, Freebies & others)     0.000000
Gold discount                                          0.000000
Brand pack discount                                    0.000000
Total                                                  0.000000
Rating                                                88.316683
Review                                                98.611697
Cancellation / Rejection reason                       99.127621
Restaurant compensation (Cancellation)                99.376202
Restaurant penalty (Rejection)                        99.985929
KPT duration (minutes)                                 1.383612
Rider wait time (minutes)                              0.787956
Order Ready Marked                                     0.000000
Customer complaint tag                                97.800291
Customer ID                                            0.000000
dtype: float64

Menampilkan hanya kolom yang mising values

In [21]:
missing_values = df.isnull().sum()
missing_values_percentage = (df.isnull().sum() / len(df)) * 100

In [22]:
missing_df = pd.DataFrame({
    "Missing Values": missing_values,
    "Percentage": missing_values_percentage
})
missing_df[missing_df["Missing Values"] > 0]

                                        Missing Values  Percentage
Instructions                                     20601   96.623048
Discount construct                                5498   25.786783
Rating                                           18830   88.316683
Review                                           21025   98.611697
Cancellation / Rejection reason                  21135   99.127621
Restaurant compensation (Cancellation)           21188   99.376202
Restaurant penalty (Rejection)                   21318   99.985929
KPT duration (minutes)                             295    1.383612
Rider wait time (minutes)                          168    0.787956
Customer complaint tag                           20852   97.800291

Dari table dapat diketahui ada 7 kolom yang presentasenya melewati 70% dan sebaiknya dihapus

###**MENGATASI MISING VALUES**

Menghapus mising values yang presentasenya lebih dari 70%

In [46]:
df.drop(['Instructions', 'Rating',
         'Review', 'Cancellation / Rejection reason', 'Restaurant compensation (Cancellation)',
         'Restaurant penalty (Rejection)', 'Customer complaint tag'], axis=1, inplace=True)

Melakukan imputasi pada mising values yang presentasinya 1,5%

In [53]:
df['KPT duration (minutes)'].dropna().describe()

count    21026.000000
mean        17.332960
std          6.283388
min          0.000000
25%         13.380000
50%         16.330000
75%         20.050000
max         90.870000
Name: KPT duration (minutes), dtype: float64

In [54]:
df['KPT duration (minutes)'] = df['KPT duration (minutes)'].fillna(df['KPT duration (minutes)'].dropna().mean())

In [55]:
df['KPT duration (minutes)'].dropna().describe()

count    21321.000000
mean        17.332960
std          6.239765
min          0.000000
25%         13.430000
50%         16.430000
75%         19.980000
max         90.870000
Name: KPT duration (minutes), dtype: float64

##**Tahap 3 : Melakukan pengecekan duplikat**

In [23]:
duplicate_rows = df.duplicated().sum()
print(f"Jumlah data duplikat: {duplicate_rows}")

Jumlah data duplikat: 0

Dapat diketahui tidak ada data yang di duplikat

##**Tahap 4 : melakukan pengecekan outliers**

In [30]:
print(df.describe())

       Restaurant ID      Order ID  Bill subtotal  Packaging charges  \
count   2.132100e+04  2.132100e+04   21321.000000       21321.000000
mean    2.074413e+07  6.354622e+09     750.076838          32.564592
std     2.447193e+05  1.230263e+08     498.759428          22.235898
min     2.032061e+07  6.086767e+09      50.000000           0.000000
25%     2.063570e+07  6.250751e+09     459.000000          18.450000
50%     2.065987e+07  6.357715e+09     629.000000          28.450000
75%     2.088265e+07  6.456827e+09     899.000000          39.950000
max     2.152306e+07  6.573392e+09   16080.000000         603.000000

       Restaurant discount (Promo)  \
count                 21321.000000
mean                     65.091816
std                      85.401604
min                       0.000000
25%                       0.000000
50%                      80.000000
75%                     100.000000
max                    4020.000000

       Restaurant discount (Flat offs, Freebies & others)  Gold discount  \
count                                       21321.000000    21321.000000
mean                                           31.795058        0.099128
std                                           131.487091        3.264261
min                                             0.000000        0.000000
25%                                             0.000000        0.000000
50%                                             0.000000        0.000000
75%                                             0.000000        0.000000
max                                          7787.000000      280.100000

       Brand pack discount         Total       Rating  \
count         21321.000000  21321.000000  2491.000000
mean              3.039324    682.616113     4.356885
std              17.070780    465.313977     1.181472
min               0.000000     52.500000     1.000000
25%               0.000000    387.450000     4.000000
50%               0.000000    597.450000     5.000000
75%               0.000000    837.900000     5.000000
max             554.800000  12663.000000     5.000000

       Restaurant compensation (Cancellation)  Restaurant penalty (Rejection)  \
count                              133.000000                             3.0
mean                               356.409549                             0.0
std                                328.128240                             0.0
min                                 83.580000                             0.0
25%                                191.950000                             0.0
50%                                272.580000                             0.0
75%                                397.840000                             0.0
max                               3236.980000                             0.0

       KPT duration (minutes)  Rider wait time (minutes)
count            21026.000000               21153.000000
mean                17.332960                   4.825070
std                  6.283388                   4.982591
min                  0.000000                   0.100000
25%                 13.380000                   1.000000
50%                 16.330000                   3.100000
75%                 20.050000                   7.400000
max                 90.870000                  73.800000

Menampilkan outliers di setiap kolom

In [31]:
for col in df.select_dtypes(include=['number']).columns:
    mean = df[col].mean()
    std = df[col].std()
    lower_bound = mean - (3 * std)
    upper_bound = mean + (3 * std)

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    print(f"Outliers di kolom {col}: {len(outliers)} baris")

Outliers di kolom Restaurant ID: 28 baris
Outliers di kolom Order ID: 0 baris
Outliers di kolom Bill subtotal: 269 baris
Outliers di kolom Packaging charges: 298 baris
Outliers di kolom Restaurant discount (Promo): 111 baris
Outliers di kolom Restaurant discount (Flat offs, Freebies & others): 479 baris
Outliers di kolom Gold discount: 28 baris
Outliers di kolom Brand pack discount: 586 baris
Outliers di kolom Total: 296 baris
Outliers di kolom Rating: 0 baris
Outliers di kolom Restaurant compensation (Cancellation): 1 baris
Outliers di kolom Restaurant penalty (Rejection): 0 baris
Outliers di kolom KPT duration (minutes): 310 baris
Outliers di kolom Rider wait time (minutes): 281 baris

##**Tahap 5 : Melakukan pengecekan nilai yang tidak konsisten**

In [56]:
df

,Restaurant ID,Subzone,City,Order ID,Delivery,Distance,Items in order,Total,KPT duration (minutes),Rider wait time (minutes),Order Ready Marked,Customer ID
0,20320607,Sector 4,Delhi NCR,6168884918,Zomato Delivery,3km,"1 x Grilled Chicken Jamaican Tender, 1 x Grill...",666.75,18.35000,11.6,Correctly,5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...
1,20320607,Sector 4,Delhi NCR,6170707559,Zomato Delivery,2km,"1 x Peri Peri Fries, 1 x Fried Chicken Angara ...",1054.20,16.95000,3.6,Correctly,0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...
2,20320607,Sector 4,Delhi NCR,6169375019,Zomato Delivery,<1km,1 x Bone in Peri Peri Grilled Chicken,241.50,14.05000,12.2,Correctly,f93362f5ce5382657482d164e368186bcec9c6225fd93d...
3,20320607,Sector 4,Delhi NCR,6151677434,Zomato Delivery,2km,"1 x Fried Chicken Ghostbuster Tender, 1 x Anga...",567.00,19.00000,3.3,Correctly,1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...
4,20320607,Sector 4,Delhi NCR,6167540897,Zomato Delivery,2km,"1 x Peri Peri Krispers, 1 x Fried Chicken Anga...",529.20,15.97000,1.0,Correctly,d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...
...,...,...,...,...,...,...,...,...,...,...,...,...
21316,21467440,Chittaranjan Park,Delhi NCR,6568490993,Zomato Delivery,5km,1 x Fried Chicken Desi Peri Peri Bites (Bone),441.00,14.32000,9.0,Correctly,c6ee80eb35f2ef1630fd93ea88f8c0ac27eff57229a6d5...
21317,21467440,Chittaranjan Park,Delhi NCR,6564842673,Zomato Delivery,5km,1 x Fried Chicken 65 Masala Boneless Bites,508.62,17.33296,10.8,Missed,d2a0153ba6512894c1bebe974f6898ba10df50abc2c954...
21318,21523055,Sector 4,Delhi NCR,6553527557,Zomato Delivery,8km,1 x Korean Fried Chicken Slider,451.50,16.27000,9.4,Incorrectly,0b6168cbaf96aa5a0ae6b46d19d83ec9cad0d9508d43d7...
21319,21523055,Sector 4,Delhi NCR,6541170157,Zomato Delivery,9km,1 x Ooh Saucy Fries,355.95,12.77000,1.3,Correctly,410b3e056e511e3423d9497c629ca897f91cace2a2a732...
21320,21523055,Sector 4,Delhi NCR,6543973010,Zomato Delivery,3km,1 x Grilled Chicken Jamaican Slider,304.50,16.52000,8.7,Correctly,1f885b307de98a52c7b6f75a8813cc130e3049ad0be017...

In [ ]:
for col in df.select_dtypes(include=['object']).columns:
    print(f"Kolom {col}:")
    print(df[col].value_counts(), "\n")

###**Data Reduction**

In [48]:
df.columns

Index(['Restaurant ID', 'Subzone', 'City', 'Order ID', 'Order Status',
       'Delivery', 'Distance', 'Items in order', 'Discount construct',
       'Bill subtotal', 'Restaurant discount (Promo)',
       'Restaurant discount (Flat offs, Freebies & others)', 'Gold discount',
       'Brand pack discount', 'Total', 'KPT duration (minutes)',
       'Rider wait time (minutes)', 'Order Ready Marked', 'Customer ID'],
      dtype='object')

In [49]:
df.columns = df.columns.str.strip()

In [50]:
df.drop(['Order Status', 'Discount construct',
         'Bill subtotal', 'Restaurant discount (Flat offs, Freebies & others)', 'Restaurant discount (Promo)',
         'Brand pack discount', 'Gold discount'], axis=1, inplace=True)

In [51]:
df.columns

Index(['Restaurant ID', 'Subzone', 'City', 'Order ID', 'Delivery', 'Distance',
       'Items in order', 'Total', 'KPT duration (minutes)',
       'Rider wait time (minutes)', 'Order Ready Marked', 'Customer ID'],
      dtype='object')

Saya menghapus kolom tersebut karena tidak relevan dengan insight yang saya hasilkan. Saya mau dari dataset ini berfokus pada "Apakah kurir harus menunggu lebih lama untuk pesanan dengan jarak jauh?" atau "item apa yang membutuhkan waktu lama untuk dibuat?" sehingga saya menghapus kolom yang tidak saya butuhkan.

In [57]:
df.dtypes

Restaurant ID                  int64
Subzone                       object
City                          object
Order ID                       int64
Delivery                      object
Distance                      object
Items in order                object
Total                        float64
KPT duration (minutes)       float64
Rider wait time (minutes)    float64
Order Ready Marked            object
Customer ID                   object
dtype: object